import {
  MainBoardBox,
  MainContentBox,
  MainContentDataBox,
  MainContentTitleBox
} from "styles/MainStyle";

export default function MainIndexScreen() {
  return (
    <MainContentBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
      <MainBoardBox>
        <MainContentTitleBox></MainContentTitleBox>
        <MainContentDataBox></MainContentDataBox>
      </MainBoardBox>
    </MainContentBox>
  );
}
